### PR TITLE
Use PSR-4 and some another hotfixes

### PR DESCRIPTION
**Pull request by malukenho**

### CODE REVIEW

**Comment by henriquemoody** [comment]
Much better, thanks @malukenho!

**Comment by kinncj** [comment]
Why PSR-4? :-) I'm always in favour of PSR-0 due to the structure that I like and the proposal made years and years ago...

And share the same reasons as the @doctrine guys :-)

I think we can discuss about this... only the PSR-4, the other changes are good :+1: 

@henriquemoody , looks Marco Piveta's arguments: https://groups.google.com/forum/#!searchin/php-fig/PSR-0/php-fig/feDfmLvYJuc/XVsKvAobKwsJ

**Comment by henriquemoody** [comment]
I agree using PSR-4 since it does not breaks PSR-0.

**Comment by malukenho** [comment]
@kinncj I think if a feature is marked as deprecated is reason enough.
Btw, It's can be used with `PSR-0` too.

_" It is fully interoperable, and can be used in addition to any other autoloading specification, including PSR-0.[...]"_ - from [PSR-4 Specification](http://www.php-fig.org/psr/psr-4/).

IMHO, has no way to don't use PSR-4.
So, If necessary I can PR again to revert.

/cc @henriquemoody

**Comment by malukenho** [comment]
ping @Ocramius

**Comment by henriquemoody** [comment]
@kinncj, I agree with Marco Piveta's arguments when he said that using PSR-0 enforces you to have a more organized code structure but since we can use PSR-4 and PSR-0 together I see no point to do not use it  - and see no point to do use it too.
Since it is already here and it is a recommendation of @php-fig just let it be @malukenho.

**Comment by kinncj** [comment]
@malukenho , the feature was deprecated only because that people can't think in the same way as @Ocramius pointed.

My Point is: this project structure will have an enforcement to code organization, as the other projects... I have no issues using the PSR-4 autoloader, my only concern is about this project structure.

Anyway, thanks for the contribution, looks good.

ps: we need to test this code base while it's _skinny_

**Pull request merged**
